language:
    - cpp

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
    - mkdir build
    - cd build
    - cmake ..
    - make flash
