language:
    - cpp

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
    - git clone https://github.com/mariuszsikora/dl_tutorials.git ../dl_tutorials
    - mkdir build
    - cd build
    - cmake ..
    - make flash

notifications:
    email: false
